version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Oumayma@12345
      MYSQL_DATABASE: ems
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./ems-backend
      dockerfile: Dockerfile
    image: ems-backend-backend
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ems
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Oumayma@12345
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./ems-frontend/ems-frontend
      dockerfile: Dockerfile
    image: ems-backend-frontend
    container_name: react-app
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
