name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images with docker-compose
        run: |
          docker compose -f docker-compose.yaml build

      - name: Tag and push backend image
        run: |
          docker tag springboot-app ${{ secrets.DOCKERHUB_USERNAME }}/ems-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ems-backend:latest

      - name: Tag and push frontend image
        run: |
          docker tag react-app ${{ secrets.DOCKERHUB_USERNAME }}/ems-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ems-frontend:latest